// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_api.Api.Data;

#nullable disable

namespace backend_api.Api.Migrations
{
    [DbContext(typeof(QuantIQContext))]
    [Migration("20260318033214_AddNewsAndComments")]
    partial class AddNewsAndComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend_api.Api.Models.Candle", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Symbol", "Timestamp");

                    b.HasIndex(new[] { "Symbol", "Timestamp" }, "IX_Candles_Symbol_Time");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("backend_api.Api.Models.CashWallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WalletID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal?>("AvailableBalance")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 4)")
                        .HasComputedColumnSql("([Balance]-[LockedAmount])", true);

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("LoanAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("LockedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.HasKey("WalletId")
                        .HasName("PK__CashWall__84D4F92E6EACE5E0");

                    b.HasIndex(new[] { "UserId" }, "UQ__CashWall__1788CCADC377DAFB")
                        .IsUnique();

                    b.ToTable("CashWallets");
                });

            modelBuilder.Entity("backend_api.Api.Models.CorporateAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ActionId")
                        .HasName("PK__CorporateActions");

                    b.HasIndex("Symbol");

                    b.HasIndex(new[] { "PaymentDate", "Status" }, "IX_CorporateActions_PaymentDate_Status");

                    b.ToTable("CorporateActions", (string)null);
                });

            modelBuilder.Entity("backend_api.Api.Models.DepositRequest", b =>
                {
                    b.Property<long>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DepositID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DepositId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.HasKey("DepositId")
                        .HasName("PK__DepositRequests");

                    b.HasIndex(new[] { "Status" }, "IX_DepositRequests_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_DepositRequests_UserID");

                    b.HasIndex(new[] { "OrderCode" }, "UQ_DepositRequests_OrderCode")
                        .IsUnique();

                    b.ToTable("DepositRequests", (string)null);
                });

            modelBuilder.Entity("backend_api.Api.Models.KycDocument", b =>
                {
                    b.Property<int>("KycId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KycID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KycId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CardType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ExpiryDate")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HomeTown")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.HasKey("KycId")
                        .HasName("PK__KycDocuments");

                    b.HasIndex(new[] { "Status" }, "IX_KycDocuments_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_KycDocuments_UserID");

                    b.ToTable("KycDocuments", (string)null);
                });

            modelBuilder.Entity("backend_api.Api.Models.MarginRatio", b =>
                {
                    b.Property<int>("RatioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RatioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatioId"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("InitialRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("MaintenanceRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("RatioId")
                        .HasName("PK__MarginRa__FBB7F82CA2252F6C");

                    b.HasIndex("Symbol");

                    b.ToTable("MarginRatios");
                });

            modelBuilder.Entity("backend_api.Api.Models.NewsArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("ArticleId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Symbol", "PublishedAt")
                        .HasDatabaseName("IX_NewsArticles_Symbol_Date");

                    b.ToTable("NewsArticles", (string)null);
                });

            modelBuilder.Entity("backend_api.Api.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("OrderID");

                    b.Property<decimal?>("AvgMatchedPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MatchedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("RequestQty")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAFF43CAF5F");

                    b.HasIndex("Symbol");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("backend_api.Api.Models.Portfolio", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("([TotalQuantity]-[LockedQuantity])", true);

                    b.Property<decimal?>("AvgCostPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("LockedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TotalQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId", "Symbol");

                    b.HasIndex("Symbol");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("backend_api.Api.Models.RiskAlert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlertID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Rtt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.HasKey("AlertId")
                        .HasName("PK__RiskAlerts");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_RiskAlerts_CreatedAt");

                    b.HasIndex(new[] { "UserId" }, "IX_RiskAlerts_UserID");

                    b.ToTable("RiskAlerts", (string)null);
                });

            modelBuilder.Entity("backend_api.Api.Models.StockComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CommentId");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_StockComments_Symbol");

                    b.HasIndex("UserId");

                    b.ToTable("StockComments", (string)null);
                });

            modelBuilder.Entity("backend_api.Api.Models.Symbol", b =>
                {
                    b.Property<string>("Symbol1")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Symbol");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Symbol1");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("backend_api.Api.Models.Transaction", b =>
                {
                    b.Property<long>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TransID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RefID");

                    b.Property<DateTime?>("TransTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.HasKey("TransId")
                        .HasName("PK__Transact__9E5DDB1C74131A74");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("backend_api.Api.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserID");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("INACTIVE");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend_api.Api.Models.Candle", b =>
                {
                    b.HasOne("backend_api.Api.Models.Symbol", "SymbolNavigation")
                        .WithMany("Candles")
                        .HasForeignKey("Symbol")
                        .IsRequired()
                        .HasConstraintName("FK_Candles_Symbols");

                    b.Navigation("SymbolNavigation");
                });

            modelBuilder.Entity("backend_api.Api.Models.CashWallet", b =>
                {
                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithOne("CashWallet")
                        .HasForeignKey("backend_api.Api.Models.CashWallet", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CashWallets_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.CorporateAction", b =>
                {
                    b.HasOne("backend_api.Api.Models.Symbol", "SymbolNavigation")
                        .WithMany("CorporateActions")
                        .HasForeignKey("Symbol")
                        .IsRequired()
                        .HasConstraintName("FK_CorporateActions_Symbols");

                    b.Navigation("SymbolNavigation");
                });

            modelBuilder.Entity("backend_api.Api.Models.DepositRequest", b =>
                {
                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany("DepositRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_DepositRequests_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.KycDocument", b =>
                {
                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany("KycDocuments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_KycDocuments_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.MarginRatio", b =>
                {
                    b.HasOne("backend_api.Api.Models.Symbol", "SymbolNavigation")
                        .WithMany("MarginRatios")
                        .HasForeignKey("Symbol")
                        .IsRequired()
                        .HasConstraintName("FK_Margin_Symbols");

                    b.Navigation("SymbolNavigation");
                });

            modelBuilder.Entity("backend_api.Api.Models.Order", b =>
                {
                    b.HasOne("backend_api.Api.Models.Symbol", "SymbolNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Symbol")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Symbols");

                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("SymbolNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.Portfolio", b =>
                {
                    b.HasOne("backend_api.Api.Models.Symbol", "SymbolNavigation")
                        .WithMany("Portfolios")
                        .HasForeignKey("Symbol")
                        .IsRequired()
                        .HasConstraintName("FK_Portfolios_Symbols");

                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Portfolios_Users");

                    b.Navigation("SymbolNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.RiskAlert", b =>
                {
                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany("RiskAlerts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RiskAlerts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.StockComment", b =>
                {
                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_StockComments_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.Transaction", b =>
                {
                    b.HasOne("backend_api.Api.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_api.Api.Models.Symbol", b =>
                {
                    b.Navigation("Candles");

                    b.Navigation("CorporateActions");

                    b.Navigation("MarginRatios");

                    b.Navigation("Orders");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("backend_api.Api.Models.User", b =>
                {
                    b.Navigation("CashWallet");

                    b.Navigation("DepositRequests");

                    b.Navigation("KycDocuments");

                    b.Navigation("Orders");

                    b.Navigation("Portfolios");

                    b.Navigation("RiskAlerts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
